Add a choice to import archived Trello cards or not
linearapp/linear-import pull request #33
Opened 2020-08-30 15:18 UTC by jerryskye

Hello! Thank you for creating this project :blush:
I noticed that the Trello JSON contains archived cards. I've added support for choosing whether we want to import the archived items or not. Let me know what you think :wink:
Stay awesome! :wave:

2020-10-07 17:02 UTC, rlargman requested changes
Good catch here! One small suggestion: I think it makes sense to default to _not_ import the archived issues rather than the reverse, as that is the general recommendation.

2020-10-07 17:02 UTC, rlargman commented on src/importers/trelloJson/index.ts
> +    message: 'Would you like to import the archived cards as well?',
```suggestion
    message: 'Would you like to import the archived cards as well (not recommended)?',
```

2020-10-07 17:02 UTC, rlargman commented on src/importers/trelloJson/index.ts
> +    default: true,
```suggestion
    default: false,
```

2020-10-09 12:19 UTC, jerryskye commented
Thank you for your review! I didn't want to change the default behaviour, but this makes more sense :blush: I think I'm going to change the question to `'Would you like to discard the archived cards?'`

2020-10-09 15:40 UTC, rlargman approved these changes
Excellent, thanks again!

2020-10-14 18:03 UTC, merged